### ISSUE TITLE
Settlement Innovation Component

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#41]
**Component**: Innovations
**Being used here:**
http://localhost:3333/settlements/1234/log
Click innovations

**Task List**

- [ ] Hit (x) button should remove that innovation (just like with all components, it's pending until they hit confirm)
- [ ] Get game_assets connected
- [ ] Load the innovations list from game_assets into the dropdown
- [ ] Selecting an innovation from the dropdown should add it to the pending innovations list
- [ ] cross reference game_assets innovations to get the proper names from the innovations state.

**Comment by CalebKester** [comment]
back to me, i got a bit more work on this before it's ready for programming

**Comment by CalebKester** [comment]
Closing this until we get the design
