### ISSUE TITLE
Playtest Feedback

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#86]
Here’s my list from last night:
- [x] SFA, I need to unfilter these so they show up in fighting arts.
- [x] Brain damage. When you take a Light wound, you check the box. However when you gain more insanity you’re not supposed to uncheck the box. Not sure how we handle this (maybe we just log this as a feature to rollout when we get departing working). #88
- [ ]  Courage and Understanding abilitites
- [ ] Survivor Weapon
- [x]  Settlement Weapon mastery abilities 
- [ ]  Notes
- [x]  A survivor log would be mega helpful #87
- [ ]  Expansion monsters i don’t think are hooked up properly.
- [x] Assets cancel doesn't work.

API Q’s
- [x]  Settlement survivor. The api doesn’t seem to count the first survivor limit so i need to browse some FAQ’s - https://github.com/toconnell/kdm-manager/issues/417
- [x] Bitter Frenzy text needs to get updated (I’ll submit a PR for this)
- [ ]  SotF didn’t seem to give the stats to new survivors.

**Comment by CalebKester** [comment]
@toconnell for the principles, does the api only give current survivor the stat boost and not newborn?

e.g. Trigger SotF Principle, all current survivors get +1 str, +1 eva.
e.g.2. Newborn created after SotF has 0 str and 0 eva

**Comment by CalebKester** [comment]
Question 2. In order to get FA/Abilities for expansions do I have to enable them for the settlement? Is there a way to just have the assets and not them on the timeline?

**Comment by toconnell** [comment]
@CalebKester 

- SotF updates all living survivors (whether they're born or not).
- I'll look at the PR when I get back in front of my real computer (tomorrow)
- re: expansions, if you don't enable the content, it doesn't show up in the `game_assets` element. If you want to look up all Fighting Arts, for example, we could set it up so that a GET to `/fighting_arts` just dumps you a list of all FA definitions. What do you think about that?
